import '../../static/globals.css'
import '../../static/fonts.css'
export const metadata = {
  title: 'Coming Soon',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body style={{backgroundPosition:'center',backgroundImage:"url('/images/backgrounds/coming-soon-background.webp')",fontFamily:'dosislight'}}>
       {children}
      </body>
    </html>
  )
}
