export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="preload stylesheet" href="/static/css/fonts.css" as="style"  />        
        <link rel="preload stylesheet" href="/static/css/globals.css" as="style"  />
      </head>
      <body>{children}</body>
    </html>
  )
}
