import "./globals.css";
import './fonts.css'
import NavBar from "@/Components/Globals/NavBar/NavBar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{backgroundImage:"url('/images/backgrounds/8.de377256.jpeg')",fontFamily:'dosislight'}}>
        <div style={{backgroundImage:`url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32' width='32' height='32' fill='none' stroke='%23f1f5f9'%3e%3cpath d='M0 .5H31.5V32'/%3e%3c/svg%3e")`}}>
          <NavBar/>
          {children}
        </div>
      </body>
    </html>
  );
}
